apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gmd8ok8o8-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:563c8e6adc8d6ee2a5a73f33a8dcd0a96ff3eff3@sha256:1c8482f3f4c7ef4cb959eefdcecaea8fc2bd04129f25325fe3095ae982c71d75
          name: container-image
