apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gmd8ok8o8-dotnet-basic
  janus-idp.io/tekton: gmd8ok8o8-dotnet-basic
  backstage.io/kubernetes-id: gmd8ok8o8-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gmd8ok8o8-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
